services:
  backend-test:
    build:
      context: .
    networks:
      - reverse-proxy
      - pronomodotest-network
    depends_on:
      - db-test

  db-test:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=azbecbaboevav
      - MYSQL_DATABASE=pronosmodo
      - MYSQL_USER=modo
      - MYSQL_PASSWORD=
    ports:
      - "3307:3306"
    networks:
      - pronomodotest-network
    volumes:
      - db_data_test:/var/lib/mysql

networks:
  reverse-proxy:
    external: true

  pronomodotest-network:
    driver: bridge

volumes:
  db_data_test:
