services:
  backend:
    build:
      context: .
    networks:
      - reverse-proxy
      - pronomodo-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=azbecbaboevav
      - MYSQL_DATABASE=pronosmodo
      - MYSQL_USER=modo
      - MYSQL_PASSWORD=
    ports:
      - "3306:3306"
    networks:
      - pronomodo-network
    volumes:
      - db_data:/var/lib/mysql

networks:
  reverse-proxy:
    external: true

  pronomodo-network:
    driver: bridge

volumes:
  db_data:
